name: Java Lib CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Dummy gradle.properties
      shell: bash
      run: |
         mkdir -p ~/.gradle/
         echo "GRADLE_USER_HOME=$HOME/.gradle" >> $GITHUB_ENV
         echo ossrhUsername=dummy > ~/.gradle/gradle.properties
         echo ossrhPassword=dummy >> ~/.gradle/gradle.properties  
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Run unit tests
      run: ./gradlew test
